service: motomarket-telegrambot

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-dir-config-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
  

functions:
  processWebhook:
    handler: src/handler.processWebhook
    events:
      - http:
          path: webhook
          method: post
          cors: true